// <auto-generated />
namespace VidlyUA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddMovieDBContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMovieDBContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201807261521431_Add-Movie-DBContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
